name: flutter_apns
description: APNS push notification plugin. Uses firebase_messaging on Android, but replaces it on iOS with custom implementation.
version: 2.0.0
homepage: https://github.com/mwaylabs/flutter-apns

plugin:
  platforms:
    android:
      pluginClass: FirebasePushConnector
    ios:
      pluginClass: ApnsPushConnector

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_messaging: ^14.0.3
  flutter_apns_only: ^1.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
